title: "Kevin Xie's Personal Website"
description: "Sharing my experiences, thoughts, and academic progress."
theme: jekyll-theme-minimal  # Change this to another theme if desired
show_downloads: false
